export const SET_LANG = 'SET_LANG';

export const SET_TEXT = 'SET_TEXT';

export const SET_IMAGE_URL = 'SET_IMAGE_URL';

export const EDIT_COMPONENT = 'EDIT_COMPONENT';
export const CANCEL_EDITION = 'CANCEL_EDITION';

export const SET_STYLE_VALUE = 'SET_STYLE_VALUE';
export const ADD_STYLE = 'ADD_STYLE';
export const DELETE_STYLE = 'DELETE_STYLE';

export const APPEND_COMPONENT = 'APPEND_COMPONENT';
export const PREPEND_COMPONENT = 'PREPEND_COMPONENT';

export const DELETE_COMPONENT = 'DELETE_COMPONENT';

export const NAVIGATE_PREV = 'NAVIGATE_PREV';
export const NAVIGATE_NEXT = 'NAVIGATE_NEXT';
export const NAVIGATE_UP = 'NAVIGATE_UP';
export const NAVIGATE_DOWN = 'NAVIGATE_DOWN';
